### ISSUE TITLE
Implement forcekill

### ISSUE THREAD

**Issue by vinicpac** [lac-dcc/honey-potion#20]
Implement the example [forcekill](https://github.com/lac-dcc/honey-potion/tree/master/benchmarks/programs/forcekill) using elixir.

**Comment by Dwctor** [comment]
With b1d3cca we now have a fully working Forcekill example within Honey-Potion exclusively. Although the behavior is a bit different (prints killed elements always instead of after 30 seconds) I have deemed that that is close enough to the intended purpose of Forcekill and so will be closing this issue.
